#!/usr/bin/env bash
set -o errexit      
set -o nounset

readonly PROGDIR=$(readlink -m "$(dirname "$0")")
readonly pilldaycounter="$PROGDIR/pilldaycounter"
readonly conf="$PROGDIR/pilldays.cfg"
readonly pic=$(find "$PROGDIR"/pictures/ -type f |sort -R | tail -1)
readonly to="myPrecious@gmail.com"
readonly name="Precious"

function sendMessage(){
	if [ ! -e "$conf" ];then
		bash "$pilldaycounter"
		echo "[*] a new configfile has been created, re-run the script!"
		exit 1
	fi
	source "$conf"
	message=""
	if [ "$day" -le 21 ];then
		local message="Take the pill"
	elif [ "$day" -le 28 ];then
		local message="Buy pills "$name"!"
	fi
	echo "Day: $day" | mutt -s "$message" "$to" -a "$pic"
}

main(){
	sendMessage
	bash "$pilldaycounter"
}
main
