#!/usr/bin/env bash
set -o errexit      
set -o nounset

readonly PROGDIR=$(readlink -m "$(dirname "$0")")
readonly pilldaycounter="$PROGDIR/pilldaycounter"
readonly conf="$PROGDIR/pilldays.cfg"
readonly pic=$(find "$PROGDIR"/pictures/ -type f |sort -R | tail -1)
readonly to="myPrecious@gmail.com"
readonly name="Precious"

function sendMessage(){
	if [ ! -e "$conf" ];then
		bash "$pilldaycounter"
		echo "[*] a new configfile has been created, re-run the script!"
		exit 1
	fi
	source "$conf"
	if [ "$day" -le 21 ];then
		echo "Day: $day" | mutt -s "Pill reminder: take the pill, "$name"!" "$to" -a "$pic"
	elif [ "$day" -le 28 ];then
		echo "Day: $day" | mutt -s "Pill reminder: buy pills my Precious!" "$to" -a "$pic"
	fi
}

main(){
	sendMessage
	bash "$pilldaycounter"
}
main
