#!/bin/bash
#
# CD to flac archiver script

RED='\033[1;31m'
GREEN='\033[1;32m'
NC='\033[0m'

function displayTitle(){
	printf "....................................\n"
	printf ":    CD to flac archiver srcipt    :\n"
	printf "....................................\n"
}

function error(){
		if [ "$?" -ne 0 ];then
			printf "${RED}[-] Error: something went wrong...\n${NC}"
			exit 1
		fi
}

function isFlacInstalled(){
	
		man flac >/dev/null 2>&1
	
		if [ "$?" -ne 0 ];then
			printf "${RED}[-] Error: flac is not installed on this system!\n${NC}"
			echo "Enter your password to install it!"
			sudo apt-get install flac -y
		fi
}

function isCDparanoiaInstalled(){
	
		man cdparanoia > /dev/null 2>&1
	
		if [ "$?" -ne 0 ];then
			printf "${RED}[-] Error: cdparanoia is not installed on this system!\n${NC}"
			echo "Enter your password to install it!"
			sudo apt-get install cdparanoia -y
		fi
}

function archiving(){
		
		printf "${GREEN}[-] Enter folder name:\n${NC}"
		read -r folder
		mkdir -p $folder
		cd $folder || exit 1
		echo "[-] Please insert CD!"
		read -p "[-] Press [Enter] key to start backup ..."
		sleep 2
		echo "[-] Archiving has been started ..."
		sleep 2
		cdparanoia -B
		error
		echo "[-] Converting to flac format ..."
		flac --keep-foreign-metadata *.wav
		error
		echo "[-] Removing wav files"
		rm -rf *.wav
		error
		printf "${GREEN}[-] Done...\n${NC}"
}

function main(){
	displayTitle
	isFlacInstalled
	isCDparanoiaInstalled
	archiving
}

main
