#!/usr/bin/python

# Multiplies characters

import sys

if len(sys.argv) == 3:
	print sys.argv[1] * int(sys.argv[2])


else:
    print "Usage:\nEnter 2 command line arguments!\nExample: %s A 100" % sys.argv[0]
    
