#!/usr/bin/python

# Repeats the given chars

import sys

if len(sys.argv) == 3:
	print sys.argv[1] * int(sys.argv[2])


else:
    print "Usage:\nEnter 2 arguments: 1 char and 1 integer; they'll be multiplied\nExample: %s A 100" % sys.argv[0]
    
