#!/bin/bash

checkRecquirements(){
	local programs=( "cdparanoia" "flac" )

	for i in "${programs[@]}"
	do
		[ -x "$(which "$i")" ] && echo "[*] "$i" OK" || echo "[-] Error: "$i" not istalled"
	done
}
