#!/bin/bash
set -x

IP='10.0.0.100'
USERNAME='root'
PASSWORD='root'

ID='garden'
FPS=15
DURATION=10
FOLDER="/home/$USER/recordings/$ID"
STREAM="rtsp://$USERNAME:$PASSWORD@$IP/axis-media/media.amp"


check(){
	if ! ffmpeg -v grep && ffprobe -v grep; then
		echo '[-] install ffmpeg and ffprobe!'
	elif ! ffmpeg -v grep && ffprobe -v grep; then
		echo '[-] install ffmpeg and ffprobe!'	
	fi
}

record(){	
	while true
		do

			TODAY=$(date +%Y-%m-%d)

			mkdir -p "$FOLDER/$TODAY"

			ffmpeg -i $STREAM -r $FPS -t $DURATION "/$FOLDER/$TODAY/$(date +%Y-%m-%d_%H%M%S_$ID).mp4"

		done
}

main(){
	check
	record
}

main
