#!/bin/bash

AXIS_IP="192.168.1.100"
FROM_FOLDER="/mnt/recordings"
TO_FOLDER="/mnt/recordings/$AXIS_IP"

function delete_oldest(){
	MAX=99
	SPACE=`df -h | tr -d "%" | awk '/sda/ { print $5 }'`
	
	if [ "$SPACE" -ge "$MAX" ];then
		rm -rf `ls -t | tail -n 1`
	fi
}


function arrange(){

for i in `find $FROM_FOLDER -name *.mkv | awk -F '_' '{print $5}'|awk -F '/' '{print $2}'| sort | uniq`; 
	do 
		if [ ! -d $i ]; then
			mkdir -p $i
			mv -u `find $FROM_FOLDER -name $i*.mkv` $i
		else
			mv -u `find $FROM_FOLDER -name $i*.mkv` $i
		fi

	done
}
main(){
	mkdir -p $TO_FOLDER
	cd $TO_FOLDER	
	#delete_oldest
	arrange
}

main

exit 0


