#!/bin/bash

function welcome(){
	echo '[-] Full Circle Magazine downloader script'
	echo ''
}


function get_issues(){
	from=0
	to=0
	echo 'enter issue FROM:'
	read from
	echo 'enter issue TO:'
	read to
}


function download_issues(){
	for i in `seq $from $to`

		do
		echo "[-] debug: DOWNLOADLING : $i "
		wget http://dl.fullcirclemagazine.org/issue$[i]_en.pdf
		done
		
}


function main(){
	welcome
	get_issues
	download_issues
}

main

exit 0
