#!/bin/bash

function create_lockfile(){

        local PROGNAME=`basename $0`
        local LOCKFILE=/var/lock/lockfile.${PROGNAME}
        echo "The lockfile's name : ${LOCKFILE}"
        touch $LOCKFILE
}

function check_lockfile(){
        if [ -f $LOCKFILE ]; then
                echo "The lockfile is already there, exiting..."
                exit 1
        fi
}


function main(){
        check_lockfile
        create_lockfile
}

main
