#!/usr/bin/env python
# -*- coding:utf-8 -*-

"""
Mass renamer script that renames arbitrary strings in filenames
Usage:
	as root: touch /usr/bin/renamer
	copy the script to that file,
	give it permissions for instance chmod 700 /usr/bin/renamer
	than you can invoke it from any folder you are actually working in
"""

import os

class FilesToRename():
	
	def show_files(self):
		print "Files in current folder:\n"
		print os.listdir('.')
		
	def rename(self):
		print "\n"
		src = raw_input("Enter the string to rename: ")
		
		for i in os.listdir('.'):
			extension = i[-3:]
		
		if src in extension.lower():
			print("Are you sure you want to modify the extension?")
			raw_input("Press Enter to continue..., CTRL + C to exit\n> ")
		
		dst = raw_input("Enter new string: ")
		print "\nStrings to replaced: %s ---> %s" % (src, dst)
		raw_input("Press Enter to continue..., CTRL + C to exit\n> ")
		for filename in os.listdir("."): 
				os.rename(filename, filename.replace(src, dst))

a = FilesToRename()

a.show_files()
a.rename()
a.show_files()
