#!/usr/bin/env python
# -*- coding:utf-8 -*-

import os

class FilesToRename():
	
	def show_files(self):
		print "Files in current folder:\n"
		print os.listdir('.')
		
	def show_extension(self):
		for i in os.listdir('.'):
			ext = i[-3:]
			print ext

	def rename(self):
		print "\n"
		src = raw_input("Enter the string to rename: ")
		dst = raw_input("Enter new string: ")
		print "\nStrings to replaced: %s ---> %s" % (src, dst)
		raw_input("Press Enter to continue..., CTRL + C to exit\n> ")
		for filename in os.listdir("."): 
				os.rename(filename, filename.replace(src, dst))

f = FilesToRename()

f.show_files()
f.rename()
f.show_files()

