#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
replaces hyphenated and odd characters in file or foldernames

Usage:
	as root: touch /usr/bin/replacer
	copy this script to that file, give it a proper permission, for instance chmod 700 /usr/bin/replacer
	than you can invoke it from any folder you are actually working in :-)
"""

import os

chars = {
    'á': 'a',
    'à': 'a',
    'é': 'e',
    'ê': 'e',
    'í': 'i',
    'ó': 'o',
    'ö': 'o',
    'ő': 'o',
    'ú': 'u',
    'ü': 'u',
    'ű': 'u',

    'Á': 'A',
    'É': 'E',
    'Í': 'I',
    'Ó': 'O',
    'Ö': 'O',
    'Ő': 'O',
    'Ú': 'U',
    'Ü': 'U',
    'Ű': 'U',

    ' ': '.',
    '-': '_',
    ':': '.',
    '::': '_',
    '..': '.',
    '._.':'-',
    '._':'_',
    '°':'.',
    'YouTube':''
}

for src, dst in chars.items():
    for filename in os.listdir("."):
        if filename[0] == ' ' or filename[:1] == ' ':
            dst = ''
        os.rename(filename, filename.replace(src, dst))
