#!/bin/bash
# syncroniser script from an AXIS video server				06.10.2015

AXIS_IP='192.168.1.100'
AXIS_PORT='21'
USER='root'
PASS='root'
LOCAL_FOLDER='/mnt/recordings'
AXIS_SD='/var/spool/storage/SD_DISK'

usage() {
	readonly PROGNAME=`basename $0`

	cat <<- EOF
	usage of $PROGNAME script
	
	the script will exit if it has already been started
	to make it run in every minute: 
	
	crontab -e and append this:
	
	*/1 * * * *  /path/to/script/$PROGNAME
	EOF
}

function is_external_hdd(){
	
		ls $LOCAL_FOLDER >/dev/null
		
		if [ $? -ne 0 ];then
			echo 'there is no HDD attached'
			exit 1
		fi
}

function no_multiple_instance(){

		if [ "$(pgrep -x $(basename $0))" != "$$" ]; then
			echo 'only one instance is allowed'
			exit 2
		fi
}


function hdd_capacity(){
		
		SPACE=`df -h | tr -d "%" | awk '/sda/ { print $5 }'`

		if [ "$SPACE" -ge "97" ];then
			echo `date +%Y-%m-%d_%H:%M` 'hdd is 97 % full, the oldest mkv files will be deleted soon' >> error.log
		fi
		
		if [ "$SPACE" -ge "98" ];then
			rm -rf `find $LOCAL_FOLDER ! -type d -name *.mkv -printf "%T@ %p\n" | sort -n | head -n 1`
			echo `date +%Y-%m-%d_%H:%M` 'hdd is 98 % full, the oldest mkv files have been deleted' >> error.log
			exit 3	
		fi
		
		if [ "$SPACE" -ge "99" ];then
			exit 4
		fi
}

function download_from_axis(){
		
		cd $LOCAL_FOLDER
		
		wget -m --timeout=10 --tries=3 --user=$USER --password=$PASS ftp://$AXIS_IP:$AXIS_PORT/$AXIS_SD --directory-prefix=$LOCAL_FOLDER --reject "*.xml, *.db" 
		
		if [ $? -ne 0 ];then
			echo 'could not download from server'
			exit 5
		fi
}

main() {
	is_external_hdd
	hdd_capacity
	no_multiple_instance
	download_from_axis
}

main

exit 0
