#!/bin/bash
# syncronising and arranging files from an AXIS video server
# invoke the script with cron

AXIS_IP='192.168.1.10'
AXIS_PORT='21'
USER='root'
PASS='root'
LOCAL_FOLDER='/mnt/recordings'
AXIS_SD='/var/spool/storage/SD_DISK'
TO_FOLDER='/mnt/recordings/arranged'
MAX='99'					# HDD max
EXTENSION='mkv'

function usage() {
	readonly PROGNAME=`basename $0`

	cat <<- EOF
	usage of $PROGNAME script
	
	the script will exit if it has already been started
	to make it run in every minute: 
	
	crontab -e and append this:
	
	*/1 * * * *  /path/to/script/$PROGNAME
	EOF
}

function is_axis(){
	
	if ! ping -c 1 "$AXIS_IP";then
		echo "The axis server is not available..."
		exit 1
	fi
	
}

function syncronising(){
	wget -m --timeout=10 --tries=3 --user=$USER --password=$PASS ftp://$AXIS_IP:$AXIS_PORT/$AXIS_SD --directory-prefix=$LOCAL_FOLDER --reject "*.xml, *.db"
}

function delete_oldest_folder(){
	cd "$LOCAL_FOLDER" || exit 1
	if [ "$SPACE" -ge "$MAX" ];then
		rm -rf `ls -t | tail -n 1`
	fi
}

function arranging_old(){

	mkdir -p $TO_FOLDER
	cd $TO_FOLDER || exit 1

	for i in `find $LOCAL_FOLDER -name *.$EXTENSION | awk -F '_' '{print $5}'|awk -F '/' '{print $2}'| sort | uniq`; 
		do 
			if [ ! -d $i ]; then
				mkdir -p $i
				mv -u `find $LOCAL_FOLDER -name $i*.mkv` $i
			else
				mv -u `find $LOCAL_FOLDER -name $i*.mkv` $i
			fi

		done
}

function arranging(){
	
	for i in $(find $LOCAL_FOLDER -type f -name *.$EXTENSION); do

		NEWDIR=$(echo "$i" | grep -Eo '[0-9]{8}')

		if [ ! -d "/$TO_FOLDER/$NEWDIR" ]; then
			mkdir -p /$TO_FOLDER/$NEWDIR
		fi

		rsync -vah --progress $i /$TO_FOLDER/$NEWDIR/

	done
	
}

function main(){
	is_axis
	syncronising
	arranging
}

main
