#!/bin/bash
# syncronising and arranging files from an AXIS video server
# invoke the script with cron

AXIS_IP='10.0.0.100'
AXIS_PORT='21'
USER='root'
PASS='root'
LOCAL_FOLDER='/$HOME/axis'
AXIS_SD='/var/spool/storage/SD_DISK'
TO_FOLDER='/$HOME/axis_arranged/'
MAX='99'					# HDD max
EXTENSION='mkv'

function usage() {
	readonly PROGNAME=`basename $0`

	cat <<- EOF
	usage of $PROGNAME script
	
	the script will exit if it has already been started
	to make it run in every minute: 
	
	crontab -e and append this:
	
	*/1 * * * *  /path/to/script/$PROGNAME
	EOF
}

function is_axis(){
	
	if ! ping -c 1 "$AXIS_IP";then
		echo "The axis server is not available..."
		exit 1
	fi
	
}

function syncronising(){
	wget -m --timeout=10 --tries=3 --user=$USER --password=$PASS ftp://$AXIS_IP:$AXIS_PORT/$AXIS_SD --directory-prefix=$LOCAL_FOLDER --reject "*.xml, *.db"
}

function arranging(){
	
	for i in $(find "$LOCAL_FOLDER" -type f -name *."$EXTENSION"); do

	NEWDIR=$(echo "$i" | grep -Eo '[0-9]{8}' | sort | uniq)

	if [ ! -d "/$TO_FOLDER/$NEWDIR" ]; then
		mkdir -p /"$TO_FOLDER"/"$NEWDIR"
	fi

		rsync -vah --progress "$i" /"$TO_FOLDER"/"$NEWDIR"/

	done
}

function main(){
	is_axis
	syncronising
	arranging
}

main
