#!/usr/bin/python

import os
import sys

class Vivotek():
    ip = ''
    username = ''
    password = ''
    stream = '2'
    port = '554'

    def url(self):
        return ('rtsp://%s:%s@%s:%s/live%s.sdp') % (self.username,self.password,self.ip,self.port,self.stream)



"""
To Do: check out live555 
"""
