#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os, time, shutil

"""
    moves files into folders according to file creation time
"""

os.chdir('.')

for f in os.listdir('.'):
    file_creation_time = time.gmtime(os.path.getmtime(f))
    dir_creation_time = time.strftime('%Y-%m-%d', time.gmtime(os.path.getmtime(f)))

    if not os.path.isdir(dir_creation_time):
        os.mkdir(dir_creation_time)
    if '.py' in f:
        continue

    else:
        try:
            shutil.move(f, dir_creation_time)
        except:
            pass
