#!/bin/bash

echo "Watchdog started..."

while [ 1 ]; do
			LC_ALL=C nmcli -t -f TYPE,STATE dev | grep -q "^gsm:disconnected$"
			if [ $? -eq 0 ]; then
				echo 'disconnected, trying to reconnect'
			fi
			
			LC_ALL=C nmcli -t -f TYPE,STATE dev | grep -q "^gsm:connected$"
			if [ $? -eq 0 ]; then
				echo 'connected'
			fi
		
			sleep 10
	done
