#!/bin/bash

# The scipt checks for torrents in the download folder, and transfers them to synology server
#
# 12.25.2017. kerzol81
#
# Before running, a passwordless ssh key must be generated and uploaded to the server
# 
# First: run it manually, enter the password and add the server to known_host file
# Every minute with cron:
# * * * * * /usr/bin/upload2deluge

local_path='/home/zoli/Downloads/'
torrents=$(find "$local_path" -type f -name '*torrent' | wc -l)
server_path='root@10.0.0.110:/var/services/homes/z/torrents'

cd "$local_path" || exit 1

if [ "$torrents" -eq 0 ]; then	
    exit 2
fi

for i in *.torrent; do 
	scp -i ~/.ssh/id_rsa "$i" "$server_path";	
	if [ $? -ne 0 ];then
		exit 3
	fi
	echo "`date +%Y-%m-%d_@_%H:%M` $i" >> /var/log/upload2synology.log
done

find "$local_path" -type f -name '*torrent' -exec rm -f {} \;

exit 0
