#!/bin/bash

# upload2deluge - the scipt checks for torrents in the download folder, and transfers them to a dedicated torrent server
#
# 12.03.2016. kerzol81
#
# Prior to running a passwordless ssh key must be generated and uploaded to the torrent server
# run it in every minute with cron:
# * * * * * /usr/bin/upload2deluge

local_path='/home/zoli/downloads/'
torrents=`find "$local_path" -type f -name '*torrent' | wc -l`
server_path='root@10.0.0.4:/home/deluge/torrents/'

cd "$local_path"

if [ "$torrents" -eq 0 ]; then
	exit 1
fi

for i in *.torrent; do 
	scp -i ~/.ssh/id_rsa "$i" "$server_path";	
	if [ $? -ne 0 ];then
		exit 2
	fi
done

find "$local_path" -type f -name '*torrent' -exec rm -f {} \;

exit 0
