#!/bin/bash

# Prior to running a passwordless ssh key must be generated and uploaded to the server
# then run it by cron as you wish

#!/bin/bash

folder='/home/zoli/downloads/' 
server='root@10.0.0.4:/home/deluge/torrents/'
host='10.0.0.4'

cd "$folder"
torrents=`find . -type f -name '*torrent' | wc -l`

if [ "$torrents" -eq 0 ];
then
	exit 1
fi

	
for i in *.torrent
	do 
		scp -i ~/.ssh/id_rsa "$i" "$server";	
		if [ $? -ne 0 ];
			then
			exit 2
		fi
	done

find "$folder" -type f -name '*torrent' -exec rm -f {} \;

exit 0

