#!/bin/bash

folder='/home/zoli/downloads/' 
server='root@10.0.0.4:/home/deluge/torrents/'
host='10.0.0.4'

cd "$folder"

find . -type f -iname '*torrent' 2>/dev/null

if [ $? -ne 0 ];
then
	exit 1
fi


ping -c 1 $host 1>/dev/null 2>&1
	
if [ $? -ne 0 ];
then
	exit 2
fi
	
for i in *.torrent
	do 
		scp -i ~/.ssh/id_rsa "$i" "$server";	
	done

find "$folder" -type f -iname '*torrent' -exec rm -f {} \;

exit 0
