#!/bin/bash

readVars(){
	echo "Creating a cron job for Vivotek VS8102 stream recording"
	echo 'Enter IP: ' 
	read -r IP
	echo 'Enter user name: ' 
	read -r USERNAME
	echo 'Enter password: ' 
	read -r PASSWORD
	echo 'Enter stream number: '
	read -r STREAM
}

createCronJob(){
	cd /tmp/ || exit 1
	rm /tmp/*.vivotek 2>/dev/null
	touch "$IP".vivotek
	CRONJOB="*/5 * * * * /usr/bin/vrecord $IP $USERNAME $PASSWORD $STREAM"
	{
		echo "# m h  dom  dow  command"
		echo "# "
		echo "# Cron job was created: $(date +%Y-%m-%d) at $(date +%H:%M)"
		echo "#                            <IP>      <U>  <PW>    <STREAM>"
		echo "$CRONJOB"
	
	} >> "$IP".vivotek
	crontab "$IP".vivotek
	echo "The following configuration has been created: "
	crontab -l
	rm /tmp/*.vivotek
}



main(){
	readVars
	createCronJob
	}
	
main
exit 0
