#!/bin/sh

# HUAWEI E3372 USB LTE

set -x

# Switch to modem mode

DefaultVendor=0x$(lsusb | grep -i huawei | awk '{print $6}' | awk -F ":" '{print $1}')
DefaultProduct=0x$(lsusb | grep -i huawei | awk '{print $6}' | awk -F ":" '{print $2}')

if [ "$DefaultVendor" = "0x" ] || [ "$DefaultProduct" = "0x" ];then
	echo '[-] Missing USB device'
	exit 2 
fi

if ! usb_modeswitch --default-vendor "$DefaultVendor" --default-product "$DefaultProduct" --huawei-new-mode;then
      exit 4
fi


# Test web interface
if curl --max-time 3 "http://192.168.8.1" --silent &>/dev/null; then
    echo 'Connection to web interface successful'
else
    echo 'Unable to connect to web interface. Exiting'
    exit 3
fi

# Obtain SessionID and __RequestVerificationToken
SesTokInfo=$(curl "http://192.168.8.1/api/webserver/SesTokInfo" --silent)
SessionID=$(echo "$SesTokInfo" | grep "SessionID=" | cut -b 20-147)
__RequestVerificationToken=$(echo "$SesTokInfo" | grep "TokInfo" | cut -b 10-41)

# Enable data
curl "http://192.168.8.1/api/dialup/mobile-dataswitch" \
     -H "Cookie: SessionID=$SessionID" \
     -H 'Origin: http://192.168.8.1' \
     -H 'Accept-Encoding: gzip, deflate' \
     -H 'Accept-Language: en-US,en;q=0.9,uk;q=0.8,ru;q=0.7' \
     -H 'User-Agent: Mozilla/5.0' \
     -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
     -H 'Accept: */*' \
     -H 'Referer: http://192.168.8.1/html/mobileconnection.html' \
     -H 'X-Requested-With: XMLHttpRequest' \
     -H 'Connection: keep-alive' \
     -H "__RequestVerificationToken: $__RequestVerificationToken" \
     -H 'DNT: 1' \
     --data '<?xml version="1.0" 
encoding="UTF-8"?><request><dataswitch>1</dataswitch></request>' \
     --compressed \
     --insecure \
     --silent \
     --output /dev/null
curl "http://192.168.8.1/api/dialup/mobile-dataswitch" \
     -H "Cookie: SessionID=$SessionID" \
     -H 'DNT: 1' \
     -H 'Accept-Encoding: gzip, deflate' \
     -H 'Accept-Language: en-US,en;q=0.9,uk;q=0.8,ru;q=0.7' \
     -H 'User-Agent: Mozilla/5.0' \
     -H 'Accept: */*' \
     -H 'Referer: http://192.168.8.1/html/mobileconnection.html' \
     -H 'X-Requested-With: XMLHttpRequest' \
     -H 'Connection: keep-alive' \
     --compressed \
     --insecure \
     --silent \
     --output /dev/null

# Check status
# <ConnectionStatus>900</ConnectionStatus> - Connecting
# <ConnectionStatus>901</ConnectionStatus> - Connected
# <ConnectionStatus>902</ConnectionStatus> - Disconnected
# <ConnectionStatus>903</ConnectionStatus> - Disconnecting
status=$(curl "http://192.168.8.1/api/monitoring/status" \
     -H "Cookie: SessionID=$SessionID" \
     -H 'DNT: 1' \
     -H 'Accept-Encoding: gzip, deflate' \
     -H 'Accept-Language: en-US,en;q=0.9,uk;q=0.8,ru;q=0.7' \
     -H 'User-Agent: Mozilla/5.0' \
     -H 'Accept: */*' \
     -H 'Referer: http://192.168.8.1/html/mobileconnection.html' \
     -H 'X-Requested-With: XMLHttpRequest' \
     -H 'Connection: keep-alive' \
     --compressed \
     --insecure \
     --silent |\
     grep '<ConnectionStatus>' | cut -b 19-21)
if [[ $status -eq 900 ]]; then
    echo 'Status 900 (Connecting)'
elif [[ $status -eq 901 ]]; then
    echo 'Status 901 (Connected)'
elif [[ $status -eq 901 ]]; then
    echo 'Status 902 (Disconnected)'
elif [[ $status -eq 901 ]]; then
    echo 'Status 903 (Disconnecting)'
else
    echo 'Unknown status'
fi
