#!/bin/bash

#HUAWEI

DefaultVendor=0x$(lsusb | grep -i huawei | awk '{print $6}' | awk -F ":" '{print $1}')
DefaultProduct=0x$(lsusb | grep -i huawei | awk '{print $6}' | awk -F ":" '{print $2}')

usb_modeswitch -v "$DefaultVendor" -p "$DefaultProduct"	-W
