#!/bin/bash

FOLDER=$1

WORK_FOLDER="/share/$FOLDER/"
ARRANGED_FOLDER="/share/$FOLDER/videos_by_day"
EXTENSION="mkv"

if [ "$#" -eq 0 ]; then  
	echo '[-] You need add an argument folder! ex.:'
	echo './arranger <folder>'
	/sbin/write_log "$ arranger needs a folder as argument" 1
	exit 1 
fi 

for i in $(find "$WORK_FOLDER" -type f -name *."$EXTENSION"); do
	DAY=$(echo "$i" | awk -F '/' '{print $8}' | awk -F '_' '{print $1}' | sort | uniq)
	
	if [ ! -d "/$ARRANGED_FOLDER/$DAY" ]; then
			mkdir -p /"$ARRANGED_FOLDER"/"$DAY"
	fi
	
	cd "$ARRANGED_FOLDER"/"$DAY"
	
	if ! ln -sfn "$i"; then
			echo "[-] Error: Could not create symbolic links"
	fi
	
done
/sbin/write_log "$1 arranger was succesful" 4
exit 0
