#!/bin/bash

FILE="/home/zoli/Desktop/ips"

declare -a myarray
let i=0
while IFS=$'\n' read -r line_data; do

    myarray[i]="${array_element}" 
    ((++i))
done < $FILE

PORT='554'

for i in "${myarray[@]}";do

	if ! $(nc -z "$i" "$PORT");then
		echo "$i" "$PORT" "OFF"
	else
		echo "$i" "$PORT" "ON"
	fi

done

